kramdown:
  html_to_native: true
  parse_block_html: true

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

title: Emiliano Ciavatta
tagline: Student in Engineering and Computer Science
description: Student in Engineering and Computer Science at the University of Bologna passionate about IT security
url: eciavatta.it
twitter:
  username: e_ciavatta
  card: summary
social:
  name: Emiliano Ciavatta
  links:
    - https://twitter.com/e_ciavatta
    - https://www.facebook.com/eciavatta
    - https://www.linkedin.com/in/eciavatta
    - https://github.com/eciavatta
    - https://keybase.io/eciavatta
